import { BogClassification, PortfolioAging, RepaymentDaily } from '@/types/mfi';
import { format } from 'date-fns';

export function exportToCSV<T extends Record<string, any>>(
  data: T[],
  filename: string,
  columns: { key: keyof T; header: string }[]
): void {
  if (data.length === 0) return;

  const headers = columns.map((col) => col.header).join(',');
  const rows = data.map((row) =>
    columns
      .map((col) => {
        const value = row[col.key];
        // Escape quotes and wrap in quotes if contains comma
        const str = String(value ?? '');
        if (str.includes(',') || str.includes('"') || str.includes('\n')) {
          return `"${str.replace(/"/g, '""')}"`;
        }
        return str;
      })
      .join(',')
  );

  const csv = [headers, ...rows].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  downloadBlob(blob, `${filename}.csv`);
}

export function exportBogClassificationCSV(data: BogClassification[], orgName: string): void {
  exportToCSV(data, `bog-classification-${format(new Date(), 'yyyy-MM-dd')}`, [
    { key: 'bog_bucket', header: 'Classification' },
    { key: 'loan_count', header: 'Loan Count' },
    { key: 'outstanding_balance', header: 'Outstanding Balance (GHS)' },
    { key: 'provision_rate', header: 'Provision Rate' },
    { key: 'provision_amount', header: 'Provision Amount (GHS)' },
  ]);
}

export function exportPortfolioAgingCSV(data: PortfolioAging[]): void {
  exportToCSV(data, `portfolio-aging-${format(new Date(), 'yyyy-MM-dd')}`, [
    { key: 'loan_id', header: 'Loan ID' },
    { key: 'client_name', header: 'Client Name' },
    { key: 'principal', header: 'Principal (GHS)' },
    { key: 'outstanding_balance', header: 'Outstanding Balance (GHS)' },
    { key: 'days_overdue', header: 'Days Overdue' },
    { key: 'bog_bucket', header: 'BOG Classification' },
  ]);
}

export function exportRepaymentsCSV(data: RepaymentDaily[]): void {
  exportToCSV(data, `repayments-daily-${format(new Date(), 'yyyy-MM-dd')}`, [
    { key: 'payment_date', header: 'Date' },
    { key: 'total_amount', header: 'Amount (GHS)' },
    { key: 'payment_count', header: 'Payment Count' },
  ]);
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// PDF export using browser print
export function exportToPDF(elementId: string, title: string): void {
  const element = document.getElementById(elementId);
  if (!element) return;

  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        body { font-family: 'Inter', system-ui, sans-serif; padding: 40px; }
        h1 { font-size: 24px; margin-bottom: 8px; color: #1e3a5f; }
        .subtitle { color: #6b7280; font-size: 14px; margin-bottom: 24px; }
        table { width: 100%; border-collapse: collapse; font-size: 12px; }
        th { text-align: left; padding: 12px 8px; border-bottom: 2px solid #e5e7eb; 
             font-weight: 600; color: #6b7280; text-transform: uppercase; font-size: 11px; }
        td { padding: 10px 8px; border-bottom: 1px solid #f3f4f6; }
        tr:nth-child(even) { background: #f9fafb; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 500; }
        .badge-current { background: #d1fae5; color: #065f46; }
        .badge-watch { background: #fef3c7; color: #92400e; }
        .badge-substandard { background: #fed7aa; color: #9a3412; }
        .badge-doubtful { background: #fecaca; color: #991b1b; }
        .badge-loss { background: #fecaca; color: #7f1d1d; }
        .text-right { text-align: right; }
        .footer { margin-top: 32px; font-size: 11px; color: #9ca3af; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      <div class="subtitle">Generated on ${format(new Date(), 'MMMM d, yyyy \'at\' h:mm a')}</div>
      ${element.outerHTML}
      <div class="footer">Report generated by MFI Dashboard</div>
    </body>
    </html>
  `);

  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => {
    printWindow.print();
    printWindow.close();
  }, 250);
}
